name: Check the package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Check the package for type errors
      run: mypy .

    - name: Check the package for lints
      run: ruff check .

    - name: Check the package for poor code style
      run: ruff format --check .

    - name: Check the package's docstrings
      run: pydoclint .

    - name: Test the package
      run: pytest
